# Site settings
author: Jacqueline Lam
title: Building a CLI Data Gem: for Indecisive Shoppers
header-img: img/home-bg.png
email: jacqueline.karin.lam@gmail.com
copyright_name: Jacqueline Lam
description: > # this means to ignore newlines until "baseurl:"
  A reflection on my first project at Flatiron School. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jacqueline-lam

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
